ruby "2.1.4"
gem "rbzip2"         # http://rubygems.org/gems/rbzip2
gem "libxml-xmlrpc"  # http://rubygems.org/gems/libxml-xmlrpc
gem "rmagick"        # http://rubygems.org/gems/rmagick
gem "zipruby"        # http://rubygems.org/gems/zipruby
gem "ruby-audio"     # http://rubygems.org/gems/ruby-audio
gem "ruby-minisat"   # http://rubygems.org/gems/ruby-minisat
